name: Pandonia-UHCAPI
version: 2.0
main: fr.pandonia.uhcapi.API
author: TheMachuPichu
commands:
  mumble:
    aliases: [ mb, mumb, mumbleoerthyon, oerthyonmumble, mumblelink, oerthyonlink ]
  enchant:
  finish:
  helpop:
  vanish:
  host:
    aliases: [ h ]
  inv:
    aliases: [ inventory ]
  revive:
  rules:
  scenario:
    aliases: [ scenarios ]
  tc:
    aliases: [ teamcoords, tl, coords, coord ]
  view:
    aliases: [ invsee ]
  vote:
  preload:
  tprandom:
  alerts:
  whitelist:
    aliases: [ wl ]
  tphere:
  health:
  viewoffline:
  disperse:
  groupe:
    aliases: [ groupes ]
  near:
    aliases: [ playersnear,playernear ]